/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserFrontend;

import Domain.Config;
import Domain.Nupkg;
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Font;
import java.awt.Rectangle;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.util.regex.Pattern;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author marcocspc
 */
public class MainWindow extends javax.swing.JFrame {

	/**
	 * Creates new form MainWindow
	 */
	public static Nupkg nupkg;

	public static String TEXT_ID = "ID";
	public static String TEXT_TITLE = "Title";
	public static String TEXT_VERSION = "Version";
	public static String TEXT_AUTHORS = "Authors";
	public static String TEXT_OWNERS = "Owners";
	public static String TEXT_SUMMARY = "Summary";
	public static String TEXT_PROJECT_URL = "Project URL";
	public static String TEXT_LICENSE_URL = "License URL";
	public static String TEXT_ICON_URL = "Icon URL";
	public static String TEXT_TAGS = "Tags";
	public static String TEXT_DEPENDENCIES = "Dependencies";
	public static String TEXT_INSTALLER_TYPE = "Installer Type";
	public static String TEXT_UNATTENDED_ARGUMENTS = "Unattended Arguments";
	public static String TEXT_INTALLER_X86 = "32-bit Installer";
	public static String TEXT_INTALLER_X64 = "64-bit Installer";

	public MainWindow() {
		initComponents();

		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
			JOptionPane.showMessageDialog(rootPane, "Error!\n" + ex.getMessage());
		}

		this.setDefaultCloseOperation(EXIT_ON_CLOSE);
		this.setLocationRelativeTo(null);
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                dialogDep = new javax.swing.JDialog();
                jPanel4 = new javax.swing.JPanel();
                fieldDep = new javax.swing.JTextField();
                btnAddDep = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                listDep = new javax.swing.JList<>();
                btnRemDep = new javax.swing.JButton();
                jPanel1 = new javax.swing.JPanel();
                jScrollPane3 = new javax.swing.JScrollPane();
                jPanel2 = new javax.swing.JPanel();
                idField = new javax.swing.JTextField();
                titleField = new javax.swing.JTextField();
                versionField = new javax.swing.JTextField();
                authorsField = new javax.swing.JTextField();
                ownersField = new javax.swing.JTextField();
                summaryField = new javax.swing.JTextField();
                projectURLField = new javax.swing.JTextField();
                licenseURLField = new javax.swing.JTextField();
                iconURLField = new javax.swing.JTextField();
                tagsField = new javax.swing.JTextField();
                dependenciesField = new javax.swing.JTextField();
                dependenciesButton = new javax.swing.JButton();
                installerTypeField = new javax.swing.JTextField();
                unattendedArgumentsField = new javax.swing.JTextField();
                x86InstallerField = new javax.swing.JTextField();
                x64InstallerField = new javax.swing.JTextField();
                button32BitInstaller = new javax.swing.JButton();
                button64BitInstaller = new javax.swing.JButton();
                jPanel3 = new javax.swing.JPanel();
                newBtn = new javax.swing.JButton();
                openBtn = new javax.swing.JButton();
                saveBtn = new javax.swing.JButton();
                sairBtn = new javax.swing.JButton();
                sendBtn = new javax.swing.JButton();
                exampleBtn = new javax.swing.JButton();

                dialogDep.setMinimumSize(new java.awt.Dimension(412, 300));
                dialogDep.setModal(true);

                fieldDep.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                fieldDepFocusLost(evt);
                        }
                });
                fieldDep.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                fieldDepKeyTyped(evt);
                        }
                });

                btnAddDep.setText("+");
                btnAddDep.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddDepActionPerformed(evt);
                        }
                });

                listDep.setModel(new DefaultListModel());
                jScrollPane1.setViewportView(listDep);

                btnRemDep.setText("-");
                btnRemDep.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRemDepActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                        .addComponent(fieldDep))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAddDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRemDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAddDep))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(btnRemDep)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );

                javax.swing.GroupLayout dialogDepLayout = new javax.swing.GroupLayout(dialogDep.getContentPane());
                dialogDep.getContentPane().setLayout(dialogDepLayout);
                dialogDepLayout.setHorizontalGroup(
                        dialogDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 412, Short.MAX_VALUE)
                        .addGroup(dialogDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dialogDepLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                );
                dialogDepLayout.setVerticalGroup(
                        dialogDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
                        .addGroup(dialogDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dialogDepLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                );

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Cacao");
                setMinimumSize(new java.awt.Dimension(1200, 900));
                setPreferredSize(new java.awt.Dimension(1200, 900));
                setResizable(false);

                idField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
                idField.setForeground(new java.awt.Color(153, 153, 153));
                idField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
                idField.setText("ID");
                idField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                idFieldFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                idFieldFocusLost(evt);
                        }
                });

                titleField.setFont(new java.awt.Font("Lucida Grande", 2, 12)); // NOI18N
                titleField.setForeground(new java.awt.Color(153, 153, 153));
                titleField.setText("Title");
                titleField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                titleFieldFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                titleFieldFocusLost(evt);
                        }
                });

                versionField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
                versionField.setForeground(new java.awt.Color(153, 153, 153));
                versionField.setText("Version");
                versionField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                versionFieldFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                versionFieldFocusLost(evt);
                        }
                });

                authorsField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
                authorsField.setForeground(new java.awt.Color(153, 153, 153));
                authorsField.setText("Authors");
                authorsField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                authorsFieldFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                authorsFieldFocusLost(evt);
                        }
                });

                ownersField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
                ownersField.setForeground(new java.awt.Color(153, 153, 153));
                ownersField.setText("Owners");
                ownersField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                ownersFieldFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                ownersFieldFocusLost(evt);
                        }
                });

                summaryField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
                summaryField.setForeground(new java.awt.Color(153, 153, 153));
                summaryField.setText("Summary");
                summaryField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                summaryFieldFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                summaryFieldFocusLost(evt);
                        }
                });

                projectURLField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
                projectURLField.setForeground(new java.awt.Color(153, 153, 153));
                projectURLField.setText("Project URL");
                projectURLField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                projectURLFieldFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                projectURLFieldFocusLost(evt);
                        }
                });

                licenseURLField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
                licenseURLField.setForeground(new java.awt.Color(153, 153, 153));
                licenseURLField.setText("License URL");
                licenseURLField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                licenseURLFieldFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                licenseURLFieldFocusLost(evt);
                        }
                });

                iconURLField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
                iconURLField.setForeground(new java.awt.Color(153, 153, 153));
                iconURLField.setText("Icon URL");
                iconURLField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                iconURLFieldFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                iconURLFieldFocusLost(evt);
                        }
                });

                tagsField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
                tagsField.setForeground(new java.awt.Color(153, 153, 153));
                tagsField.setText("Tags");
                tagsField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                tagsFieldFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                tagsFieldFocusLost(evt);
                        }
                });

                dependenciesField.setEditable(false);
                dependenciesField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
                dependenciesField.setForeground(new java.awt.Color(153, 153, 153));
                dependenciesField.setText("Dependencies");

                dependenciesButton.setText("...");
                dependenciesButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                dependenciesButtonActionPerformed(evt);
                        }
                });

                installerTypeField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
                installerTypeField.setForeground(new java.awt.Color(153, 153, 153));
                installerTypeField.setText("Installer Type");
                installerTypeField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                installerTypeFieldFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                installerTypeFieldFocusLost(evt);
                        }
                });

                unattendedArgumentsField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
                unattendedArgumentsField.setForeground(new java.awt.Color(153, 153, 153));
                unattendedArgumentsField.setText("Unattended Arguments");
                unattendedArgumentsField.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                unattendedArgumentsFieldFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                unattendedArgumentsFieldFocusLost(evt);
                        }
                });

                x86InstallerField.setEditable(false);
                x86InstallerField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
                x86InstallerField.setForeground(new java.awt.Color(153, 153, 153));
                x86InstallerField.setText("32-bit Installer");

                x64InstallerField.setEditable(false);
                x64InstallerField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
                x64InstallerField.setForeground(new java.awt.Color(153, 153, 153));
                x64InstallerField.setText("64-bit Installer");

                button32BitInstaller.setText("...");

                button64BitInstaller.setText("...");
                button64BitInstaller.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                button64BitInstallerActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(unattendedArgumentsField)
                                        .addComponent(installerTypeField)
                                        .addComponent(idField)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(dependenciesField, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(x86InstallerField, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                                                        .addComponent(x64InstallerField))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(dependenciesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(button32BitInstaller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(button64BitInstaller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(titleField)
                                        .addComponent(versionField)
                                        .addComponent(authorsField)
                                        .addComponent(ownersField)
                                        .addComponent(summaryField)
                                        .addComponent(projectURLField)
                                        .addComponent(licenseURLField)
                                        .addComponent(iconURLField)
                                        .addComponent(tagsField))
                                .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(versionField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(authorsField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ownersField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(summaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(projectURLField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(licenseURLField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iconURLField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tagsField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dependenciesField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dependenciesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(installerTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unattendedArgumentsField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(x86InstallerField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(button32BitInstaller, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(x64InstallerField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(button64BitInstaller, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                                .addContainerGap(58, Short.MAX_VALUE))
                );

                jScrollPane3.setViewportView(jPanel2);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3)
                );

                newBtn.setText("New");
                newBtn.setMaximumSize(new java.awt.Dimension(100, 29));
                newBtn.setMinimumSize(new java.awt.Dimension(100, 29));
                newBtn.setPreferredSize(new java.awt.Dimension(100, 29));
                newBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                newBtnActionPerformed(evt);
                        }
                });

                openBtn.setText("Open");
                openBtn.setMaximumSize(new java.awt.Dimension(100, 29));
                openBtn.setMinimumSize(new java.awt.Dimension(100, 29));
                openBtn.setPreferredSize(new java.awt.Dimension(100, 29));

                saveBtn.setText("Save");
                saveBtn.setMaximumSize(new java.awt.Dimension(100, 29));
                saveBtn.setMinimumSize(new java.awt.Dimension(100, 29));
                saveBtn.setPreferredSize(new java.awt.Dimension(100, 29));

                sairBtn.setText("Exit");
                sairBtn.setMaximumSize(new java.awt.Dimension(100, 29));
                sairBtn.setMinimumSize(new java.awt.Dimension(100, 29));
                sairBtn.setPreferredSize(new java.awt.Dimension(100, 29));
                sairBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                sairBtnActionPerformed(evt);
                        }
                });

                sendBtn.setText("Send");
                sendBtn.setPreferredSize(new java.awt.Dimension(100, 29));
                sendBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                sendBtnActionPerformed(evt);
                        }
                });

                exampleBtn.setText("Example");
                exampleBtn.setPreferredSize(new java.awt.Dimension(100, 29));
                exampleBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                exampleBtnActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exampleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sairBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(openBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sairBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(exampleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void button64BitInstallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button64BitInstallerActionPerformed

    }//GEN-LAST:event_button64BitInstallerActionPerformed

    private void idFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFieldFocusGained
	    this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_ID);
    }//GEN-LAST:event_idFieldFocusGained

        private void idFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFieldFocusLost
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_ID);
        }//GEN-LAST:event_idFieldFocusLost

        private void titleFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_titleFieldFocusGained
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_TITLE);
        }//GEN-LAST:event_titleFieldFocusGained

        private void titleFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_titleFieldFocusLost
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_TITLE);
        }//GEN-LAST:event_titleFieldFocusLost

        private void versionFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_versionFieldFocusGained
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_VERSION);
        }//GEN-LAST:event_versionFieldFocusGained

        private void versionFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_versionFieldFocusLost
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_VERSION);
        }//GEN-LAST:event_versionFieldFocusLost

        private void authorsFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_authorsFieldFocusGained
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_AUTHORS);
        }//GEN-LAST:event_authorsFieldFocusGained

        private void authorsFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_authorsFieldFocusLost
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_AUTHORS);
        }//GEN-LAST:event_authorsFieldFocusLost

        private void ownersFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ownersFieldFocusGained
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_OWNERS);
        }//GEN-LAST:event_ownersFieldFocusGained

        private void ownersFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ownersFieldFocusLost
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_OWNERS);
        }//GEN-LAST:event_ownersFieldFocusLost

        private void btnAddDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDepActionPerformed
		if (Pattern.matches("[a-z]+", fieldDep.getText())) {
			DefaultListModel dlm = (DefaultListModel) listDep.getModel();
			dlm.addElement(fieldDep.getText());
			fieldDep.setText("");
		} else {
			JOptionPane.showMessageDialog(dialogDep, "Dependency name must have only lowercase letters.");
		}
        }//GEN-LAST:event_btnAddDepActionPerformed

        private void fieldDepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldDepKeyTyped
		if (!Pattern.matches("[a-z]+", fieldDep.getText()) && fieldDep.getText().length() > 0) {
			try {
				Robot rb = new Robot();
				rb.keyPress(KeyEvent.VK_BACK_SPACE);
				rb.keyRelease(KeyEvent.VK_BACK_SPACE);
			} catch (AWTException ex) {
				JOptionPane.showMessageDialog(null, ex.getMessage());
			}

		}
        }//GEN-LAST:event_fieldDepKeyTyped

        private void btnRemDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemDepActionPerformed
		if (listDep.getSelectedIndex() > -1) {
			DefaultListModel dlm = (DefaultListModel) listDep.getModel();
			dlm.remove(listDep.getSelectedIndex());
		}
        }//GEN-LAST:event_btnRemDepActionPerformed

        private void dependenciesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dependenciesButtonActionPerformed
		dialogDep.setLocationRelativeTo(null);
		dialogDep.setVisible(true);
        }//GEN-LAST:event_dependenciesButtonActionPerformed

        private void fieldDepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldDepFocusLost
		if (!Pattern.matches("[a-z]+", fieldDep.getText()) && fieldDep.getText().length() > 0) {
			fieldDep.setText(fieldDep.getText().substring(0, fieldDep.getText().length() - 1));
		}
        }//GEN-LAST:event_fieldDepFocusLost

        private void summaryFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_summaryFieldFocusGained
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_SUMMARY);
        }//GEN-LAST:event_summaryFieldFocusGained

        private void projectURLFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_projectURLFieldFocusGained
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_PROJECT_URL);
        }//GEN-LAST:event_projectURLFieldFocusGained

        private void licenseURLFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_licenseURLFieldFocusGained
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_LICENSE_URL);
        }//GEN-LAST:event_licenseURLFieldFocusGained

        private void iconURLFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_iconURLFieldFocusGained
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_ICON_URL);
        }//GEN-LAST:event_iconURLFieldFocusGained

        private void tagsFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tagsFieldFocusGained
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_TAGS);
        }//GEN-LAST:event_tagsFieldFocusGained

        private void installerTypeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_installerTypeFieldFocusGained
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_INSTALLER_TYPE);
        }//GEN-LAST:event_installerTypeFieldFocusGained

        private void unattendedArgumentsFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unattendedArgumentsFieldFocusGained
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_UNATTENDED_ARGUMENTS);
        }//GEN-LAST:event_unattendedArgumentsFieldFocusGained

        private void summaryFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_summaryFieldFocusLost
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_SUMMARY);
        }//GEN-LAST:event_summaryFieldFocusLost

        private void projectURLFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_projectURLFieldFocusLost
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_PROJECT_URL);
        }//GEN-LAST:event_projectURLFieldFocusLost

        private void licenseURLFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_licenseURLFieldFocusLost
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_LICENSE_URL);
        }//GEN-LAST:event_licenseURLFieldFocusLost

        private void iconURLFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_iconURLFieldFocusLost
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_ICON_URL);
        }//GEN-LAST:event_iconURLFieldFocusLost

        private void tagsFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tagsFieldFocusLost
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_TAGS);
        }//GEN-LAST:event_tagsFieldFocusLost

        private void installerTypeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_installerTypeFieldFocusLost
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_INSTALLER_TYPE);
        }//GEN-LAST:event_installerTypeFieldFocusLost

        private void unattendedArgumentsFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unattendedArgumentsFieldFocusLost
		this.defaultActionForTextFieldFocusGained((JTextField) evt.getComponent(), MainWindow.TEXT_UNATTENDED_ARGUMENTS);
        }//GEN-LAST:event_unattendedArgumentsFieldFocusLost

        private void sairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBtnActionPerformed
		System.exit(0);
        }//GEN-LAST:event_sairBtnActionPerformed

        private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
		int selectedOption = JOptionPane.showConfirmDialog(null,
			"If you continue, all fields will be erased.",
			"Are you sure?",
			JOptionPane.YES_NO_OPTION);

		if (selectedOption == JOptionPane.YES_OPTION) {
			this.setDefaults();
		}
        }//GEN-LAST:event_newBtnActionPerformed

        private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
		JOptionPane.showMessageDialog(null, "Not implemented yet.");
        }//GEN-LAST:event_sendBtnActionPerformed

        private void exampleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exampleBtnActionPerformed
		this.setExample();
        }//GEN-LAST:event_exampleBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainWindow().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField authorsField;
        private javax.swing.JButton btnAddDep;
        private javax.swing.JButton btnRemDep;
        private javax.swing.JButton button32BitInstaller;
        private javax.swing.JButton button64BitInstaller;
        private javax.swing.JButton dependenciesButton;
        private javax.swing.JTextField dependenciesField;
        private javax.swing.JDialog dialogDep;
        private javax.swing.JButton exampleBtn;
        private javax.swing.JTextField fieldDep;
        private javax.swing.JTextField iconURLField;
        private javax.swing.JTextField idField;
        private javax.swing.JTextField installerTypeField;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JTextField licenseURLField;
        private javax.swing.JList<String> listDep;
        private javax.swing.JButton newBtn;
        private javax.swing.JButton openBtn;
        private javax.swing.JTextField ownersField;
        private javax.swing.JTextField projectURLField;
        private javax.swing.JButton sairBtn;
        private javax.swing.JButton saveBtn;
        private javax.swing.JButton sendBtn;
        private javax.swing.JTextField summaryField;
        private javax.swing.JTextField tagsField;
        private javax.swing.JTextField titleField;
        private javax.swing.JTextField unattendedArgumentsField;
        private javax.swing.JTextField versionField;
        private javax.swing.JTextField x64InstallerField;
        private javax.swing.JTextField x86InstallerField;
        // End of variables declaration//GEN-END:variables

	private void defaultActionForTextFieldFocusGained(JTextField jtf, String defaultText) {
		if (!jtf.getText().equals("") && jtf.getText().equals(defaultText)) {
			Rectangle bounds = jtf.getBounds();
			bounds.setLocation(SwingUtilities.convertPoint(jtf, bounds.getLocation(), jtf.getParent()));
			jtf.setText("");
			this.setFilledFont(jtf);
			JComponent parent = (JComponent) jtf.getParent();
			parent.scrollRectToVisible(bounds);
		} else if (jtf.getText().equals("") && !jtf.getText().equals(defaultText)) {
			jtf.setText(defaultText);
			this.setDefaultFont(jtf);
		}
	}

	private void setDefaults() {
		MainWindow.nupkg = new Nupkg();

		idField.setText(MainWindow.TEXT_ID);
		titleField.setText(MainWindow.TEXT_TITLE);
		versionField.setText(MainWindow.TEXT_VERSION);
		authorsField.setText(MainWindow.TEXT_AUTHORS);
		ownersField.setText(MainWindow.TEXT_OWNERS);
		summaryField.setText(MainWindow.TEXT_SUMMARY);
		projectURLField.setText(MainWindow.TEXT_PROJECT_URL);
		licenseURLField.setText(MainWindow.TEXT_LICENSE_URL);
		iconURLField.setText(MainWindow.TEXT_ICON_URL);
		tagsField.setText(MainWindow.TEXT_TAGS);
		dependenciesField.setText(MainWindow.TEXT_DEPENDENCIES);
		installerTypeField.setText(MainWindow.TEXT_INSTALLER_TYPE);
		unattendedArgumentsField.setText(MainWindow.TEXT_UNATTENDED_ARGUMENTS);
		x86InstallerField.setText(MainWindow.TEXT_INTALLER_X86);
		x64InstallerField.setText(MainWindow.TEXT_INTALLER_X64);

		this.setDefaultFont(idField);
		this.setDefaultFont(titleField);
		this.setDefaultFont(versionField);
		this.setDefaultFont(authorsField);
		this.setDefaultFont(ownersField);
		this.setDefaultFont(summaryField);
		this.setDefaultFont(projectURLField);
		this.setDefaultFont(licenseURLField);
		this.setDefaultFont(iconURLField);
		this.setDefaultFont(tagsField);
		this.setDefaultFont(dependenciesField);
		this.setDefaultFont(installerTypeField);
		this.setDefaultFont(unattendedArgumentsField);
		this.setDefaultFont(x86InstallerField);
		this.setDefaultFont(x64InstallerField);
	}

	private void setExample() {
		idField.setText(Config.DEFAULT_EXAMPLE_TEXT_ID);
		titleField.setText(Config.DEFAULT_EXAMPLE_TEXT_TITLE);
		versionField.setText(Config.DEFAULT_EXAMPLE_TEXT_VERSION);
		authorsField.setText(Config.DEFAULT_EXAMPLE_TEXT_AUTHORS);
		ownersField.setText(Config.DEFAULT_EXAMPLE_TEXT_OWNERS);
		summaryField.setText(Config.DEFAULT_EXAMPLE_TEXT_SUMMARY);
		projectURLField.setText(Config.DEFAULT_EXAMPLE_TEXT_PROJECT_URL);
		licenseURLField.setText(Config.DEFAULT_EXAMPLE_TEXT_LICENSE_URL);
		iconURLField.setText(Config.DEFAULT_EXAMPLE_TEXT_ICON_URL);
		tagsField.setText(Config.DEFAULT_EXAMPLE_TEXT_TAGS);
		dependenciesField.setText(Config.DEFAULT_EXAMPLE_TEXT_DEPENDENCIES);
		installerTypeField.setText(Config.DEFAULT_EXAMPLE_TEXT_INSTALLER_TYPE);
		unattendedArgumentsField.setText(Config.DEFAULT_EXAMPLE_TEXT_UNATTENDED_ARGUMENTS);
		x86InstallerField.setText(Config.DEFAULT_EXAMPLE_TEXT_INTALLER_X86);
		x64InstallerField.setText(Config.DEFAULT_EXAMPLE_TEXT_INTALLER_X64);

		this.setFilledFont(idField);
		this.setFilledFont(titleField);
		this.setFilledFont(versionField);
		this.setFilledFont(authorsField);
		this.setFilledFont(ownersField);
		this.setFilledFont(summaryField);
		this.setFilledFont(projectURLField);
		this.setFilledFont(licenseURLField);
		this.setFilledFont(iconURLField);
		this.setFilledFont(tagsField);
		this.setFilledFont(installerTypeField);
		this.setFilledFont(unattendedArgumentsField);
	}

	private void setFilledFont(JTextField jtf) {
		Font font = new Font("Tahoma", Font.PLAIN, 13);

		jtf.setFont(font);
		jtf.setForeground(Color.BLACK);
	}

	private void setDefaultFont(JTextField jtf) {
		Font font = new Font("Lucida", Font.ITALIC, 13);

		jtf.setFont(font);
		jtf.setForeground(new Color(204, 204, 204));
	}
}
